Repository sanders41/python-project-generator, pull requests merged in 2024-09, with the labels that each got.

#439 Fix warnings with new clippy version
  src/config.rs
  src/project_info.rs
Labels: skip-changelog

#440 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#445 Add line break to dependabot day question
  src/project_info.rs
Labels: bug

#446 Add option to pyo3 justfile to build in release mode
  src/project_generator.rs
  src/snapshots/python_project__project_generator__tests__save_justfile_maturin.snap
Labels: enhancement

#449 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#450 Add W rule to ruff
  src/project_generator.rs
  src/snapshots/python_project__project_generator__tests__create_poetry_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__create_setuptools_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__create_uv_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_file_no_license_application.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_apache_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_mit_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_no_license_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_pyproject_toml_file_no_license_application.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_file_no_license_application.snap
Labels: enhancement

#451 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#454 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#462 Add release drafter details to the README
  README.md
Labels: skip-changelog

#463 Add just to README
  README.md
Labels: skip-changelog

#469 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#471 Add information about options to the README
  README.md
Labels: skip-changelog

#473 Add pre-commit info to readme
  README.md
Labels: documentation, skip-changelog

#470 Add support for Pixi projects
  .github/workflows/testing.yml
  scripts/ci_run.sh
  src/github_actions.rs
  src/project_generator.rs
  src/project_info.rs
  src/python_files.rs
  src/snapshots/python_project__github_actions__tests__save_pixi_ci_testing_linux_only_file.snap
  src/snapshots/python_project__github_actions__tests__save_pixi_ci_testing_multi_os_file.snap
  src/snapshots/python_project__project_generator__tests__create_pixi_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_no_license_application.snap
Labels: enhancement

#475 Add pixi to readme
  README.md
Labels: skip-changelog

#476 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#477 Add option to specify the project uses async
  README.md
  src/cli.rs
  src/config.rs
  src/github_actions.rs
  src/licenses.rs
  src/main.rs
  src/package_version.rs
  src/project_generator.rs
  src/project_info.rs
  src/python_files.rs
  src/rust_files.rs
  src/snapshots/python_project__project_generator__tests__create_pyproject_toml_async_project.snap
  src/snapshots/python_project__project_generator__tests__save_pyo3_dev_requirements_application_file.snap
  src/snapshots/python_project__project_generator__tests__save_pyo3_dev_requirements_lib_file.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_dev_requirements_application_file.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_dev_requirements_lib_file.snap
  src/snapshots/python_project__python_files__tests__save_main_files_is_async_project-2.snap
  src/snapshots/python_project__python_files__tests__save_main_files_is_async_project.snap
  src/snapshots/python_project__python_files__tests__save_main_test_file_is_async_project.snap
Labels: enhancement

#478 Remove duplicated help info
  src/cli.rs
Labels: skip-changelog

#480 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#483 Fix issue where maturin may not install
  src/project_generator.rs
Labels: bug

#485 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#488 Add retries if checking version fails
  Cargo.lock
  Cargo.toml
  src/package_version.rs
Labels: enhancement

#489 Add string prompt
  src/project_info.rs
Labels: skip-changelog

#490 Simplify justfile generator calls
  src/project_generator.rs
  src/project_info.rs
Labels: skip-changelog

#491 Refactor __main__ generation
  src/python_files.rs
Labels: skip-changelog

#492 Change default
  src/project_generator.rs
Labels: skip-changelog

#493 Refactor config print and save
  src/config.rs
Labels: skip-changelog

#494 Add option to include docs
  README.md
  src/cli.rs
  src/config.rs
  src/github_actions.rs
  src/licenses.rs
  src/main.rs
  src/package_version.rs
  src/project_generator.rs
  src/project_info.rs
  src/python_files.rs
  src/rust_files.rs
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_pixi.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_pixi_docs.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_poetry.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_poetry_docs.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_pyo3_docs.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_setuptools.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_setuptools_docs.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_uv.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_uv_docs.snap
  src/snapshots/python_project__project_generator__tests__create_pixi_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__save_cname_file.snap
  src/snapshots/python_project__project_generator__tests__save_docs_css_file.snap
  src/snapshots/python_project__project_generator__tests__save_index_md_file.snap
  src/snapshots/python_project__project_generator__tests__save_mkdocs_yaml.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_no_license_application.snap
Labels: enhancement

#495 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#496 Refactor save_project_manager
  src/config.rs
Labels: skip-changelog

#497 Refactor load_config
  src/config.rs
  src/project_info.rs
Labels: skip-changelog

#498 Refactor prompts
  src/project_info.rs
Labels: skip-changelog

#499 Update justfile
  justfile
Labels: skip-changelog

#500 Remove unneeded trait
  src/project_info.rs
Labels: skip-changelog

#501 Refactor prompts
  src/project_info.rs
Labels: skip-changelog

#503 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#504 Refactor config to allow better testing
  src/config.rs
  src/main.rs
  src/project_info.rs
Labels: skip-changelog

#505 Fix issue where default boolean values weren't used without prompting
  src/project_info.rs
Labels: bug

#506 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#507 Refactor default_or_prompt_bool
  src/project_info.rs
Labels: skip-changelog
