Repository sanders41/python-project-generator, pull requests merged in 2024-10, with the labels that each got.

#512 Add default for enums
  src/project_info.rs
Labels: skip-changelog

#513 Add option to reset individual config values
  src/cli.rs
  src/config.rs
  src/main.rs
Labels: enhancement

#514 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#516 Refactor config_dir and config_file_path to use Rc
  src/config.rs
Labels: skip-changelog

#518 Fix artifact name in the PyPI CI
  src/github_actions.rs
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_pyo3.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_pyo3_docs.snap
Labels: bug

#519 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#520 Fix escaping in actions
  src/github_actions.rs
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_uv.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_uv_docs.snap
  src/snapshots/python_project__github_actions__tests__save_uv_ci_testing_linux_only_file.snap
  src/snapshots/python_project__github_actions__tests__save_uv_ci_testing_multi_os_file.snap
Labels: bug

#521 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#523 Add option to add extra dependencies
  README.md
  src/cli.rs
  src/config.rs
  src/github_actions.rs
  src/licenses.rs
  src/main.rs
  src/package_version.rs
  src/project_generator.rs
  src/project_info.rs
  src/python_files.rs
  src/rust_files.rs
  src/snapshots/python_project__project_generator__tests__create_setuptools_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_apache_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_mit_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_no_license_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_pyproject_toml_file_no_license_application.snap
Labels: enhancement

#524 Add option to specify version for extra dependencies
  README.md
  src/package_version.rs
  src/project_generator.rs
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pixi_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pixi_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pyo3_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pyo3_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_setuptools_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_setuptools_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_uv_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_uv_lib_with_python_extras.snap
Labels: enhancement

#526 Add option to add extra dev dependencies
  README.md
  src/cli.rs
  src/config.rs
  src/github_actions.rs
  src/licenses.rs
  src/main.rs
  src/project_generator.rs
  src/project_info.rs
  src/python_files.rs
  src/rust_files.rs
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyo3_dev_requirements_extras_file.snap
  src/snapshots/python_project__project_generator__tests__save_pyo3_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_dev_requirements_extras_file.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_with_python_dev_extras.snap
Labels: enhancement

#528 Add ASYNC ruff rule if the project is async
  src/project_generator.rs
  src/snapshots/python_project__project_generator__tests__create_pixi_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__create_poetry_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__create_pyproject_toml_async_project.snap
  src/snapshots/python_project__project_generator__tests__create_setuptools_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__create_uv_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_no_license_application.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_file_no_license_application.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyo3_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_apache_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_mit_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_no_license_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pixi_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pixi_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pyo3_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pyo3_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_setuptools_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_setuptools_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_uv_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_uv_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_pyproject_toml_file_no_license_application.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_file_no_license_application.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_with_python_dev_extras.snap
Labels: enhancement

#529 Add more checks to CI tests
  .github/workflows/testing.yml
Labels: skip-changelog

#531 Update release drafter template
  .github/release_drafter_template.yml
Labels: skip-changelog

#532 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#534 Fix issue in adding extra dev packages in uv and pixi
  src/project_generator.rs
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_with_python_dev_extras.snap
Labels: bug

#535 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#539 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#541 Fix for broken pyo3 publish action on newer ubuntu
  src/github_actions.rs
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_pyo3.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_pyo3_docs.snap
Labels: bug

#545 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#551 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#564 Add option to pass pytest arguments in justfile
  src/project_generator.rs
  src/snapshots/python_project__project_generator__tests__save_justfile_maturin.snap
  src/snapshots/python_project__project_generator__tests__save_justfile_poetry.snap
  src/snapshots/python_project__project_generator__tests__save_justfile_setuptools.snap
Labels: enhancement

#565 Fix typo in uv justfile
  src/project_generator.rs
  src/snapshots/python_project__project_generator__tests__save_justfile_maturin.snap
Labels: bug

#566 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#567 Filter snapshots to make version updates easier
  Cargo.lock
  Cargo.toml
  src/project_generator.rs
  src/snapshots/python_project__project_generator__tests__create_pixi_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__create_poetry_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__create_pyproject_toml_async_project.snap
  src/snapshots/python_project__project_generator__tests__create_uv_pyproject_toml_mit_lib.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_file_no_license_application.snap
  src/snapshots/python_project__project_generator__tests__save_pixi_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_file_no_license_application.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_poetry_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pre_commit_file.snap
  src/snapshots/python_project__project_generator__tests__save_pyo3_dev_requirements_application_file.snap
  src/snapshots/python_project__project_generator__tests__save_pyo3_dev_requirements_extras_file.snap
  src/snapshots/python_project__project_generator__tests__save_pyo3_dev_requirements_lib_file.snap
  src/snapshots/python_project__project_generator__tests__save_pyo3_pyproject_toml_with_python_dev_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_apache_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_mit_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_no_license_pyo3.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pixi_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pixi_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pyo3_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_pyo3_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_setuptools_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_setuptools_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_uv_application_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_pyproject_toml_file_uv_lib_with_python_extras.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_dev_requirements_application_file.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_dev_requirements_extras_file.snap
  src/snapshots/python_project__project_generator__tests__save_setuptools_dev_requirements_lib_file.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_file_apache_application.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_file_mit_application.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_file_no_license_application.snap
  src/snapshots/python_project__project_generator__tests__save_uv_pyproject_toml_with_python_dev_extras.snap
Labels: skip-changelog

#569 Use the new setup-uv action for uv ci
  src/github_actions.rs
  src/snapshots/python_project__github_actions__tests__save_ci_testing_linux_only_file_pyo3.snap
  src/snapshots/python_project__github_actions__tests__save_ci_testing_multi_os_file_pyo3.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_uv.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_uv_docs.snap
  src/snapshots/python_project__github_actions__tests__save_uv_ci_testing_linux_only_file.snap
  src/snapshots/python_project__github_actions__tests__save_uv_ci_testing_multi_os_file.snap
Labels: enhancement

#570 Add uv cache to github actions for uv projects
  src/github_actions.rs
  src/snapshots/python_project__github_actions__tests__save_ci_testing_linux_only_file_pyo3.snap
  src/snapshots/python_project__github_actions__tests__save_ci_testing_multi_os_file_pyo3.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_uv.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_uv_docs.snap
  src/snapshots/python_project__github_actions__tests__save_uv_ci_testing_linux_only_file.snap
  src/snapshots/python_project__github_actions__tests__save_uv_ci_testing_multi_os_file.snap
Labels: enhancement

#571 Use uv publish to publish uv projects
  src/github_actions.rs
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_uv.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_uv_docs.snap
Labels: enhancement

#572 Switch PyPI publish from tokens to trusted publisher
  README.md
  src/github_actions.rs
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_pixi.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_pixi_docs.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_poetry.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_poetry_docs.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_pyo3.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_pyo3_docs.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_setuptools.snap
  src/snapshots/python_project__github_actions__tests__save_pypi_publish_file_setuptools_docs.snap
Labels: enhancement

#573 Bump version for release
  Cargo.lock
  Cargo.toml
Labels: skip-changelog
